name: covid_19_statistique
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bubble_tab_indicator: ^0.1.6
  fl_chart: ^0.36.0
  intl: ^0.17.0
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  geolocator: ^7.0.3
  location: ^4.1.1
  http: ^0.13.3
  fluttertoast: ^8.0.6
  numberpicker: ^2.1.1
  floating_search_bar: ^0.3.0
   
  step_progress_indicator: ^0.2.5+8
  double_back_to_close_app: ^2.0.1
  scroll_snap_list: ^0.8.0
  url_launcher: ^6.0.3
  built_collection: ^5.0.0
  feature_discovery: ^0.14.0
  devicelocale: ^0.4.1
  country_codes: ^2.0.0
  
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - lib/lang/en.json
    - lib/lang/ar.json
    - assets/flags/contry.json
    - assets/flags/country_name.json
    - assets/flags/country_name_ar.json
    - assets/flags/country_server.json
    - assets/symptoms/symptoms_data.json
    - assets/flags/images/
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-SemiBold.ttf

          weight: 700
